-- Add missing PayStatus enum values
ALTER TYPE "PayStatus" ADD VALUE IF NOT EXISTS 'AUTHORIZED';
ALTER TYPE "PayStatus" ADD VALUE IF NOT EXISTS 'CAPTURED';
ALTER TYPE "PayStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
